
package views;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

import auction.Product;
import user.*;

import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.ArrayList;
import java.awt.event.ActionEvent;
import javax.swing.JPanel;
import javax.swing.JEditorPane;

public class UserInterface extends javax.swing.JFrame {

	
	static User user;
	static Seller seller;
	static Buyer buyer;
    /**
     * Creates new form NewJFrame
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        textFieldProductSoldCode = new JTextField();
        textFieldProductSoldCode.setColumns(10);
        
        textFieldName = new JTextField();
        textFieldName.setColumns(10);
        
        textFieldDescription = new JTextField();
        textFieldDescription.setColumns(10);
        
        textFieldPrice = new JTextField();
        textFieldPrice.setColumns(10);
        
        textFieldEndTime = new JTextField();
        textFieldEndTime.setColumns(10);
        
        lblCode = new JLabel("Code");
        
        lblDescription = new JLabel("Description");
        
        lblName = new JLabel("Name");
        
        lblPrice = new JLabel("Price");
        
        lblTime = new JLabel("Time");
        
        JButton btnNewButtonSell = new JButton("Sell");
        btnNewButtonSell.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Product product = new Product();    
        		
        		
        		if(!textFieldProductSoldCode.getText().equals(""))
        		{
        			product.setProductCode(Integer.parseInt((textFieldProductSoldCode.getText())));
        		}
        		if(!textFieldName.getText().equals(""))
        		{
        			product.setProductName(textFieldName.getText());
        		}
        		if(!textFieldDescription.getText().equals(""))
        		{
        			product.setDescription(textFieldDescription.getText());
        		}
        		if(!textFieldPrice.getText().equals(""))
        		{
        			product.setPrice(Float.parseFloat(textFieldPrice.getText()));
        		}
        		if(!textFieldEndTime.getText().equals(""))
        		{
        			product.setEndTime(Float.parseFloat(textFieldEndTime.getText()));
        		}
        		product.setSellerCode(seller.getCode());
        		product.setSellerName(seller.getName());
        		product.setSellerIp(seller.getMyClientIp());
        		try {
					seller.SellNewProduct(product);
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
        	}
        });
        jPanel1 = new javax.swing.JPanel();
                
                textFieldCodeProductNeeded = new JTextField();
                textFieldCodeProductNeeded.setColumns(10);
                
                textFieldSellerWanted = new JTextField();
                textFieldSellerWanted.setColumns(10);
                
                lblCode_1 = new JLabel("Code");
                
                lblSeller = new JLabel("Seller");
                
                lblAvailableProducts = new JLabel("Available Products");
                
                btnBide = new JButton("Bide");
                btnBide.addActionListener(new ActionListener() {
                	public void actionPerformed(ActionEvent e) {
                		
                	}
                });
                
                JButton btnNewButton = new JButton("Update product List");
                btnNewButton.addActionListener(new ActionListener() {
                	public void actionPerformed(ActionEvent e) {
                		ArrayList< Product > productsList = new ArrayList< Product >();
                		
                		buyer.updateProductsList();
                		productsList = buyer.getProductsList();
                		
                		textPanelproductesList.setText("");
                		String textToupdate = "";
                		for(int i = 0; i< productsList.size(); i++)
                		{
                			textToupdate = "Seller:"+textToupdate+productsList.get(i).getProductName()+"\n"+
                							"    Product code->"+productsList.get(i).getProductCode()+"\n"+
                							"    Desciption->"+productsList.get(i).getDescription()+"\n"+
                							"    Price->"+productsList.get(i).getPrice()+"\n"+
                							"    End Time->"+productsList.get(i).getEndTime()+"\n"+
                							"    Seller code->"+productsList.get(i).getSellerCode()+"\n";
                		}
                		
                		textPanelproductesList.setText(textToupdate);
                	}
                });
                        
                        textPanelproductesList = new JEditorPane();
                        
                        textField = new JTextField();
                        textField.setColumns(10);
                        
                        JLabel lblBide = new JLabel("Bide");
                
                        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                        jPanel1Layout.setHorizontalGroup(
                        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
                        		.addGroup(jPanel1Layout.createSequentialGroup()
                        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                        				.addGroup(jPanel1Layout.createSequentialGroup()
                        					.addContainerGap()
                        					.addComponent(textPanelproductesList)
                        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                        						.addGroup(jPanel1Layout.createSequentialGroup()
                        							.addGap(20)
                        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
                        								.addGroup(jPanel1Layout.createSequentialGroup()
                        									.addComponent(lblBide)
                        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                        										.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        										.addComponent(btnBide)))
                        								.addGroup(jPanel1Layout.createSequentialGroup()
                        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                        										.addComponent(lblSeller)
                        										.addComponent(lblCode_1))
                        									.addPreferredGap(ComponentPlacement.UNRELATED)
                        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                        										.addComponent(textFieldCodeProductNeeded, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        										.addComponent(textFieldSellerWanted, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))))
                        						.addGroup(jPanel1Layout.createSequentialGroup()
                        							.addPreferredGap(ComponentPlacement.RELATED)
                        							.addComponent(btnNewButton))))
                        				.addGroup(jPanel1Layout.createSequentialGroup()
                        					.addGap(100)
                        					.addComponent(lblAvailableProducts)))
                        			.addContainerGap())
                        );
                        jPanel1Layout.setVerticalGroup(
                        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
                        		.addGroup(jPanel1Layout.createSequentialGroup()
                        			.addContainerGap()
                        			.addComponent(lblAvailableProducts)
                        			.addPreferredGap(ComponentPlacement.RELATED)
                        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                        				.addGroup(jPanel1Layout.createSequentialGroup()
                        					.addGap(16)
                        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                        						.addComponent(lblCode_1)
                        						.addComponent(textFieldCodeProductNeeded, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        					.addGap(29)
                        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                        						.addComponent(lblSeller)
                        						.addComponent(textFieldSellerWanted, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        					.addGap(18)
                        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                        						.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        						.addComponent(lblBide))
                        					.addGap(29)
                        					.addComponent(btnBide)
                        					.addGap(62)
                        					.addComponent(btnNewButton))
                        				.addGroup(jPanel1Layout.createSequentialGroup()
                        					.addPreferredGap(ComponentPlacement.RELATED)
                        					.addComponent(textPanelproductesList, GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)))
                        			.addContainerGap())
                        );
                        jPanel1.setLayout(jPanel1Layout);
                        
                                jTabbedPane1.addTab("Buyer", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(30)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblName)
        						.addComponent(lblDescription)
        						.addComponent(lblPrice)
        						.addComponent(lblTime)
        						.addComponent(lblCode))
        					.addGap(44)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(textFieldEndTime, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(textFieldProductSoldCode, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(textFieldName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(textFieldDescription, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(textFieldPrice, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(136)
        					.addComponent(btnNewButtonSell)))
        			.addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(28)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textFieldProductSoldCode, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblCode))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textFieldName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblName))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textFieldDescription, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblDescription))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textFieldPrice, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblPrice))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textFieldEndTime, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblTime))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnNewButtonSell)
        			.addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jTabbedPane1.addTab("Seller", jPanel2);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(6)
        			.addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 551, GroupLayout.PREFERRED_SIZE))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(20)
        			.addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        
        panel = new JPanel();
        jTabbedPane1.addTab("Wanted products", null, panel, null);
        
        lblCode_2P2 = new JLabel("$ 123");
        
        lblCode_2P1 = new JLabel("123");
        
        lblNewLabelProductCode = new JLabel("Product code");
        
        lblPrice_1 = new JLabel("Price");
        
        lblSellerCode = new JLabel("Seller code");
        
        labelSellerCode = new JLabel("1234556");
        GroupLayout gl_panel = new GroupLayout(panel);
        gl_panel.setHorizontalGroup(
        	gl_panel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panel.createSequentialGroup()
        			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_panel.createSequentialGroup()
        					.addGap(19)
        					.addComponent(lblNewLabelProductCode))
        				.addGroup(gl_panel.createSequentialGroup()
        					.addGap(48)
        					.addComponent(lblCode_2P1)))
        			.addGap(97)
        			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblPrice_1)
        				.addComponent(lblCode_2P2))
        			.addPreferredGap(ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
        			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        				.addComponent(labelSellerCode)
        				.addComponent(lblSellerCode))
        			.addGap(117))
        );
        gl_panel.setVerticalGroup(
        	gl_panel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panel.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_panel.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabelProductCode)
        				.addComponent(lblPrice_1)
        				.addComponent(lblSellerCode))
        			.addGap(11)
        			.addGroup(gl_panel.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblCode_2P2)
        				.addComponent(lblCode_2P1)
        				.addComponent(labelSellerCode))
        			.addContainerGap(338, Short.MAX_VALUE))
        );
        panel.setLayout(gl_panel);
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	
    	
    	user = new User();
    	
    	
    	try {
			user.initialization();
			seller = new Seller(user);
	    	buyer = new Buyer(user);
	    	
	    	
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (NoSuchAlgorithmException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvalidKeySpecException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private JTextField textFieldCodeProductNeeded;
    private JTextField textFieldSellerWanted;
    private JTextField textFieldProductSoldCode;
    private JTextField textFieldName;
    private JTextField textFieldDescription;
    private JTextField textFieldPrice;
    private JTextField textFieldEndTime;
    private JLabel lblCode;
    private JLabel lblDescription;
    private JLabel lblName;
    private JLabel lblPrice;
    private JLabel lblTime;
    private JLabel lblCode_1;
    private JLabel lblSeller;
    private JLabel lblAvailableProducts;
    private JPanel panel;
    private JLabel lblCode_2P2;
    private JLabel lblCode_2P1;
    private JLabel lblNewLabelProductCode;
    private JLabel lblPrice_1;
    private JLabel lblSellerCode;
    private JLabel labelSellerCode;
    private JButton btnBide;
    private JEditorPane textPanelproductesList;
    private JTextField textField;
}

